IF OBJECT_ID ('dbo.DELETE_USER','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_USER
GO
CREATE PROCEDURE [dbo].DELETE_USER(
@ID[int]
)
AS
DELETE FROM dbo.USERS
WHERE (ID=@ID)

GO



IF OBJECT_ID ('dbo.DELETE_PATIENT','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_PATIENT
GO
CREATE PROCEDURE [dbo].DELETE_PATIENT(

@ID[int]
)
AS
DELETE FROM  dbo.PATIENTS
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.DELETE_CLINIC','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_CLINIC
GO
CREATE PROCEDURE [dbo].DELETE_CLINIC(

@ID[int]
)
AS
DELETE FROM   dbo.CLINICS
WHERE (ID=@ID)
GO



IF OBJECT_ID ('dbo.DELETE_INCIDENTS','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_INCIDENTS
GO
CREATE PROCEDURE [dbo].DELETE_INCIDENTS(


@ID[int]
)
AS
DELETE FROM dbo.INCIDENTS
WHERE (ID=@ID)
GO



IF OBJECT_ID ('dbo.DELETE_TREATMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_TREATMENT
GO
CREATE PROCEDURE [dbo].DELETE_TREATMENT(


@ID[int]
)
AS
DELETE FROM dbo.TREATMENT
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.DELETE_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_ALLERGY
GO
CREATE PROCEDURE [dbo].DELETE_ALLERGY(

@ID[int]
)
AS
DELETE FROM  dbo.ALLERGYS
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.DELETE_PATIENT_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_PATIENT_ALLERGY
GO
CREATE PROCEDURE [dbo].DELETE_PATIENT_ALLERGY(

@ID[int]
)
AS
DELETE FROM dbo.PATIENTS_ALLERGYS
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.DELETE_OVERRULED_WARNING','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_OVERRULED_WARNING
GO
CREATE PROCEDURE [dbo].DELETE_OVERRULED_WARNING(

@ID[int]
)
AS
DELETE FROM dbo.OVERRULED_WARNING
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.DELETE_APPOINTMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_APPOINTMENT
GO
CREATE PROCEDURE [dbo].DELETE_APPOINTMENT(

@ID[int]
)
AS
DELETE FROM dbo.APPOINTMENTS
WHERE (ID=@ID)
GO



IF OBJECT_ID ('dbo.DELETE_REQUEST','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_REQUEST
GO
CREATE PROCEDURE [dbo].DELETE_REQUEST(

@ID[int]
)
AS
DELETE FROM dbo.REQUESTS
WHERE (ID=@ID)
GO



IF OBJECT_ID ('dbo.DELETE_DRUG','P') IS NOT NULL
DROP PROCEDURE [dbo].DELETE_DRUG
GO
CREATE PROCEDURE [dbo].DELETE_DRUG(

@ID[int]
)
AS
DELETE FROM dbo.DRUGS
WHERE (ID=@ID)
GO

