IF OBJECT_ID ('dbo.INSERT_USER','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_USER
GO
CREATE PROCEDURE [dbo].INSERT_USER(
@USERNAME [nvarchar](50),
@PASSWORD  [nvarchar](50),
@NAME [nvarchar](50),
@ROLE [nvarchar](50)
)

AS
SET NOCOUNT ON


INSERT INTO dbo.USERS
(USERNAME,PASSWORD,NAME,ROLE)
VALUES
(@USERNAME,@PASSWORD,@NAME,@ROLE)

GO

IF OBJECT_ID ('dbo.INSERT_PATIENT','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_PATIENT
GO
CREATE PROCEDURE [dbo].INSERT_PATIENT(

@NAME [nvarchar](50),
@ADDRESS [nvarchar](50),
@SELFHARM [char],
@PROBLEM [nvarchar](50)
)

AS
SET NOCOUNT ON
INSERT INTO dbo.PATIENTS
(NAME,ADDRESS,SELFHARM,PROBLEM)
VALUES
(@NAME,@ADDRESS,@SELFHARM,@PROBLEM)
GO


IF OBJECT_ID ('dbo.INSERT_CLINIC','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_CLINIC
GO
CREATE PROCEDURE [dbo].INSERT_CLINIC(

@NAME [nvarchar](50),
@ADDRESS [nvarchar](50),
@SUPPORTS_DROP_IN [char],
@SUPPORTS_PRE_ARRANGED [char]
)

AS
SET NOCOUNT ON
INSERT INTO dbo.CLINICS
(NAME,ADDRESS,SUPPORTS_DROP_IN,SUPPORTS_PRE_ARRANGED)
VALUES
(@NAME,@ADDRESS,@SUPPORTS_DROP_IN,@SUPPORTS_PRE_ARRANGED)
GO



IF OBJECT_ID ('dbo.INSERT_INCIDENTS','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_INCIDENTS
GO
CREATE PROCEDURE [dbo].INSERT_INCIDENTS(


@PATIENT_ID [int] ,
@DETAILS[nvarchar](200) ,
@INCIDENT_DATE [date] 
)

AS
SET NOCOUNT ON
INSERT INTO dbo.INCIDENTS
(PATIENT_ID,DETAILS,INCIDENT_DATE)
VALUES
(@PATIENT_ID,@DETAILS,@INCIDENT_DATE)
GO

IF OBJECT_ID ('dbo.INSERT_TREATMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_TREATMENT
GO
CREATE PROCEDURE [dbo].INSERT_TREATMENT(


@PATIENT_ID [int] ,
@DETAILS[nvarchar](200),
@TREATMENT_DATE [date] 
)

AS
SET NOCOUNT ON
INSERT INTO dbo.TREATMENT
(PATIENT_ID,DETAILS,TREATMENT_DATE)
VALUES
(@PATIENT_ID,@DETAILS,@TREATMENT_DATE)
GO


IF OBJECT_ID ('dbo.INSERT_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_ALLERGY
GO
CREATE PROCEDURE [dbo].INSERT_ALLERGY(



@NAME[nvarchar](200)
)

AS
SET NOCOUNT ON
INSERT INTO dbo.ALLERGYS
(NAME)
VALUES
(@NAME)
GO


IF OBJECT_ID ('dbo.INSERT_PATIENT_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_PATIENT_ALLERGY
GO
CREATE PROCEDURE [dbo].INSERT_PATIENT_ALLERGY(


@PATIENT_ID [int] ,
@ALLERGY_ID [int] 
)

AS
SET NOCOUNT ON
INSERT INTO dbo.PATIENTS_ALLERGYS
(PATIENT_ID,ALLERGY_ID)
VALUES
(@PATIENT_ID,@ALLERGY_ID)
GO


IF OBJECT_ID ('dbo.INSERT_OVERRULED_WARNING','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_OVERRULED_WARNING
GO
CREATE PROCEDURE [dbo].INSERT_OVERRULED_WARNING(

@ID_PATIENTS_ALLERGYS [int],
@USERID [int]
)

AS
SET NOCOUNT ON
INSERT INTO dbo.OVERRULED_WARNING
(ID_PATIENTS_ALLERGYS,USERID)
VALUES
(@ID_PATIENTS_ALLERGYS,@USERID)
GO

IF OBJECT_ID ('dbo.INSERT_APPOINTMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_APPOINTMENT
GO
CREATE PROCEDURE [dbo].INSERT_APPOINTMENT(

@PATIENT_ID [int],
@CLINIC_ID [int] ,
@APP_DATE [date] ,
@DOCTOR [nvarchar](50) 
)

AS
SET NOCOUNT ON
INSERT INTO dbo.APPOINTMENTS
(PATIENT_ID,CLINIC_ID,APP_DATE,DOCTOR)
VALUES
(@PATIENT_ID,@CLINIC_ID,@APP_DATE,@DOCTOR)
GO


IF OBJECT_ID ('dbo.INSERT_REQUEST','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_REQUEST
GO
CREATE PROCEDURE [dbo].INSERT_REQUEST(

@PATIENT_ID [int] ,
@PATIENT_NEW_NAME [nvarchar](50),
@NEW_ADDRESS  [nvarchar](50)
)

AS
SET NOCOUNT ON
INSERT INTO dbo.REQUESTS
(PATIENT_ID,PATIENT_NEW_NAME,NEW_ADDRESS)
VALUES
(@PATIENT_ID,@PATIENT_NEW_NAME,@NEW_ADDRESS)
GO

IF OBJECT_ID ('dbo.INSERT_DRUG','P') IS NOT NULL
DROP PROCEDURE [dbo].INSERT_DRUG
GO
CREATE PROCEDURE [dbo].INSERT_DRUG(


@NAME [nvarchar](50) ,
@SIDE_EFFECTS [nvarchar](50)

)

AS
SET NOCOUNT ON
INSERT INTO dbo.DRUGS
(NAME,SIDE_EFFECTS)
VALUES
(@NAME,@SIDE_EFFECTS)
GO

