IF OBJECT_ID ('dbo.UPDATE_USER','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_USER
GO
CREATE PROCEDURE [dbo].UPDATE_USER(
@ID [int],
@USERNAME [nvarchar](50),
@PASSWORD  [nvarchar](50),
@NAME [nvarchar](50),
@ROLE [nvarchar](50)
)

AS



UPDATE dbo.USERS
SET 
USERNAME=@USERNAME,
PASSWORD=@PASSWORD,
NAME=@NAME,
ROLE=@ROLE

WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_PATIENT','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_PATIENT
GO
CREATE PROCEDURE [dbo].UPDATE_PATIENT(

@ID [int],
@NAME [nvarchar](50),
@ADDRESS [nvarchar](50),
@SELFHARM [char],
@PROBLEM [nvarchar](50)
)

AS

UPDATE dbo.PATIENTS
SET
NAME=@NAME,
ADDRESS=@ADDRESS,
SELFHARM=@SELFHARM,
PROBLEM=@PROBLEM
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_CLINIC','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_CLINIC
GO
CREATE PROCEDURE [dbo].UPDATE_CLINIC(
@ID [int],
@NAME [nvarchar](50),
@ADDRESS [nvarchar](50),
@SUPPORTS_DROP_IN [char],
@SUPPORTS_PRE_ARRANGED [char]
)

AS

UPDATE dbo.CLINICS
SET


NAME=@NAME,
ADDRESS=@ADDRESS,
SUPPORTS_DROP_IN=@SUPPORTS_DROP_IN,
SUPPORTS_PRE_ARRANGED=@SUPPORTS_PRE_ARRANGED
WHERE (ID=@ID)
GO



IF OBJECT_ID ('dbo.UPDATE_INCIDENTS','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_INCIDENTS
GO
CREATE PROCEDURE [dbo].UPDATE_INCIDENTS(

@ID [int],
@PATIENT_ID [int] ,
@DETAILS[nvarchar](200) ,
@INCIDENT_DATE [date] 
)

AS

UPDATE dbo.INCIDENTS
SET

PATIENT_ID=@PATIENT_ID,
DETAILS=@DETAILS,
INCIDENT_DATE=@INCIDENT_DATE
WHERE (ID=@ID)

GO

IF OBJECT_ID ('dbo.UPDATE_TREATMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_TREATMENT
GO
CREATE PROCEDURE [dbo].UPDATE_TREATMENT(

@ID [int],
@PATIENT_ID [int] ,
@DETAILS[nvarchar](200),
@TREATMENT_DATE [date] 
)

AS

UPDATE dbo.TREATMENT

SET

PATIENT_ID=@PATIENT_ID,
DETAILS=@DETAILS,
TREATMENT_DATE=@TREATMENT_DATE
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_ALLERGY
GO
CREATE PROCEDURE [dbo].UPDATE_ALLERGY(


@ID [int],
@NAME[nvarchar](200)
)

AS

UPDATE dbo.ALLERGYS
SET

NAME=@NAME
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_PATIENT_ALLERGY','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_PATIENT_ALLERGY
GO
CREATE PROCEDURE [dbo].UPDATE_PATIENT_ALLERGY(

@ID [int],
@PATIENT_ID [int] ,
@ALLERGY_ID [int] 
)

AS

UPDATE dbo.PATIENTS_ALLERGYS
SET


PATIENT_ID=@PATIENT_ID,
ALLERGY_ID=@ALLERGY_ID
WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_OVERRULED_WARNING','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_OVERRULED_WARNING
GO
CREATE PROCEDURE [dbo].UPDATE_OVERRULED_WARNING(

@ID [int],
@ID_PATIENTS_ALLERGYS [int],
@USERID [int]
)

AS

UPDATE dbo.OVERRULED_WARNING

SET


ID_PATIENTS_ALLERGYS=@ID_PATIENTS_ALLERGYS,
USERID=@USERID

WHERE (ID=@ID)
GO


IF OBJECT_ID ('dbo.UPDATE_APPOINTMENT','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_APPOINTMENT
GO
CREATE PROCEDURE [dbo].UPDATE_APPOINTMENT(
@ID [int],
@PATIENT_ID [int],
@CLINIC_ID [int] ,
@APP_DATE [date] ,
@DOCTOR [nvarchar](50) 
)

AS

UPDATE dbo.APPOINTMENTS

SET
PATIENT_ID=@PATIENT_ID,
CLINIC_ID=@CLINIC_ID,
APP_DATE=@APP_DATE,
DOCTOR=@DOCTOR
WHERE (ID=@ID)
GO




IF OBJECT_ID ('dbo.UPDATE_DRUG','P') IS NOT NULL
DROP PROCEDURE [dbo].UPDATE_DRUG
GO
CREATE PROCEDURE [dbo].UPDATE_DRUG(

@ID [int] ,
@NAME [nvarchar](50) ,
@SIDE_EFFECTS [nvarchar](50)

)

AS

UPDATE dbo.DRUGS

SET


NAME=@NAME,
SIDE_EFFECTS=@SIDE_EFFECTS

WHERE (ID=@ID)
GO

